apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: projen-test
build:
  artifacts:
  - image: python-pod
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - skaffold/python-pod.yml
